language: c

sudo: required

install: test -e .travis-opam.sh || wget https://raw.githubusercontent.com/ocaml/ocaml-ci-scripts/master/.travis-opam.sh

script: bash -ex .travis-opam.sh

env:
  - OCAML_VERSION=4.07

os:
  - linux

# safelist
branches:
  only:
  - master
  - develop
  - travis_test

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  keep_history: false
  on:
    branch: develop
  local_dir: /tmp/_build/default/_doc/_html/
